spring:
  datasource:
    url: jdbc:mysql://43.156.25.82:3306/ssm
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    cache: false


mybatis:
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 80