spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ssm
    username: root
    password: Slz2087789639
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    cache: false


mybatis:
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8080